<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/object/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
<?php
$breadcrum_url = '';
foreach($path as $object)
{
	$breadcrum_url .= '/' . $object->Id;
	echo '<li class="breadcrumb-item"><small><a href="', $url->get('object' . $breadcrum_url), '">', $object->getVersion()->Title, '</a></small></li>';
}
?>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Contenido</h2>
		</div>
	</div>
</div>
<div class="container_fluid">
	<div class="row content p-3">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th width="40"></th>
						<th width="50%">Nombre</th>
						<th>Estado</th>
						<th>Último Cambio</th>
					</tr>
				</thead>
				<tbody>
					<?php if( $folders ):?>
						<?php foreach($folders as $folder):?>
							<tr onclick="window.location.href = '<?=$url->get('object' . $folder->getPath($urlpath));?>'">
								<td><i class="fas fa-folder fa-2x me-3"></i></td>
								<td><?=$folder->getVersion()->Title;?></td>
								<td><?=$folder->Published;?></td>
								<td><?=App\Library\DateUtils::DateToHuman($folder->getLastChange())?><br><?=$folder->lastuser->getDisplayName()?></td>
							</tr>
						<?php endforeach;?>
					<?php endif;?>
					<?php if( $files ):?>
						<?php foreach($files as $file):?>
							<tr onclick="window.location.href = '<?=$url->get('object' . $file->getPath($urlpath));?>'">
								<td><i class="fas fa-file fa-3x me-3"></i></td>
								<td><?=$file->getVersion()->Title;?></td>
								<td><?=$file->Published?></td>
								<td><?=App\Library\DateUtils::DateToHuman($file->getLastChange())?><br><?=$file->lastuser->getDisplayName()?></td>
							</tr>
						<?php endforeach;?>
					<?php endif;?>
				</tbody>
			</thead>
		</div>
	</div>
</div>