<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/webs/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/webs/')?>">Webs</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Webs <span class="badge bg-light"><?=count($webs);?></span></h2>
		</div>
	</div>
</div>
<div class="container_fluid">
	<div class="row content p-3">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Host</th>
						<th>Tema</th>
						<th>Estado</th>
					</tr>
				</thead>
				<tbody>
					<?php if( $webs ):?>
						<?php foreach($webs as $web):?>
							<tr onclick="window.location.href = '<?=$url->get('/webs/data/' . $web->Id);?>'">
								<td><?=$web->Name;?></td>
								<td><?=$web->Host;?></td>
								<td><?=$web->getTheme() ? $web->getTheme()->Title : "";?></td>
								<td><?=$status[$web->Published];?></td>
							</tr>
						<?php endforeach;?>
					<?php endif;?>
				</tbody>
			</thead>
		</div>
	</div>
</div>