<script>
var referenceObject, itemModal;
document.addEventListener('DOMContentLoaded', (event) => {
	itemForm = document.getElementById('itemForm');
	itemModal = new bootstrap.Modal(document.getElementById('itemModal'));
	object = document.getElementById('object');
	referenceObject = new ReferenceSelect(object);
	const items = document.getElementsByClassName('item');
	for( var i = 0; i < items.length; i++) {
		items[i].addEventListener('click', function(){
			//Load menu item data to the modal
			document.getElementById('itemModalTitle').innerHTML = 'Menú "' + this.dataset.title + '"';
			document.getElementById('num').value = this.dataset.num;
			//Populate parents menu
			parent = document.getElementById('parent');
			const mainItems = document.getElementsByClassName('main-tr');
			//Clear main items
			for(i = parent.length; i >= 1; i--) {
				parent.remove(i);
			}
			for( var i = 0; i < mainItems.length; i++) {
				if( mainItems[i].dataset.num != this.dataset.num ) {
					parent.options[parent.options.length] = new Option(mainItems[i].dataset.title, mainItems[i].dataset.num);
				}
			}
			if( this.dataset.parent ) {
				parent.value = this.dataset.parent;
			}
			document.getElementById('title').value = this.dataset.title;
			itemTypeSelect = document.getElementById('itemtype');
			itemTypeSelect.value = this.dataset.type;
			modalChangeItemType(itemTypeSelect);
			if( this.dataset.type == 'reference' ) {
				referenceObject.selectItem(this.dataset.reference, this.dataset.referencetitle);
			} else if( this.dataset.type == 'link' ) {
				document.getElementById('link').value = this.dataset.link;
			}
			if( this.dataset.status == 'enabled' ) {
				document.getElementById('itemstatus').checked = true;
			} else {
				document.getElementById('itemstatus').checked = false;
			}
			itemModal.show();
		});
	}

	document.getElementById('itemtype').addEventListener('change',function(){
		modalChangeItemType(this);
	});

});

function modalChangeItemType(itemTypeSelect) {
	if( itemTypeSelect.value == 'none' || itemTypeSelect.value == 'separator' ) {
		document.getElementById('item_object').style.display = 'none';
		document.getElementById('item_link').style.display = 'none';
	} else if( itemTypeSelect.value == 'reference' ) {
		document.getElementById('item_object').style.display = 'block';
		document.getElementById('item_link').style.display = 'none';
	} else if( itemTypeSelect.value == 'link' ) {
		document.getElementById('item_link').style.display = 'block';
		document.getElementById('item_object').style.display = 'none';
	}
}

function newItem()
{
	//Load menu item data to the modal
	document.getElementById('itemModalTitle').innerHTML = 'Menú nuevo';
	document.getElementById('num').value = '';
	//Populate parents menu
	parent = document.getElementById('parent');
	const mainItems = document.getElementsByClassName('main-tr');
	//Clear main items
	for(i = parent.length; i >= 1; i--) {
		parent.remove(i);
	}
	for( var i = 0; i < mainItems.length; i++) {
		parent.options[parent.options.length] = new Option(mainItems[i].dataset.title, mainItems[i].dataset.num);
	}
	document.getElementById('title').value = '';
	itemTypeSelect = document.getElementById('itemtype');
	itemTypeSelect.value = 'reference';
	modalChangeItemType(itemTypeSelect);
	referenceObject.reset();
	document.getElementById('itemstatus').checked = true;
	itemModal.show();
}

function saveItem()
{
	data = new FormData(itemForm);
	if( data.has('status') ) {
		data.append('ItemStatus', 'enabled');
	} else {
		data.append('ItemStatus', 'disabled');
	}
	fetch('<?=$url->get('/menus/saveItem')?>', {
		method: 'POST',
		body: data,
	})
	.then((response) => response.json())
	.then((data) => {
		item = document.getElementById('item_' + data.num);
		item.querySelector('.title').innerHTML = data.title;
		itemModal.hide();
	});
}

function confirmDelete()
{
	if( window.confirm("¿Seguro quiere eliminar el menu <?=$menu->Title;?>?"))
	{
		return true;
	}
	return false;
}

</script>
<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="javascript:newItem()" class="btn btn-sm btn-primary"><i class="fa-solid fa-plus me-2"></i>Nuevo ítem</a>
				<a href="<?=$url->get('/menus/edit/') . $menu->Id;?>" class="btn btn-sm btn-primary"><i class="far fa-edit"></i> Editar</a>
				<a href="<?=$url->get('/menus/delete/') . $menu->Id;?>" class="btn btn-sm btn-danger" onclick="return confirmDelete();"><i class="fas fa-trash-alt"></i> Eliminar</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/menus/')?>">Menus</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="profile-name float-start">
				<h2 class="mb-0"><?=$menu->Title;?></h2>
				<span><?=$menu->Code;?></span>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th>Título</th>
						<th width="100">Tipo</th>
						<th>Destino</th>
						<th width="100">Estado</th>
						<th width="30"></th>
					</tr>
				</thead>
				<tbody>
<?php
$items = $menu->getItemsParent();
if( $items )
{
	foreach($items as $item)
	{
?>
				<tr class="main-tr item" id="item_<?=$item->Num?>" data-num="<?=$item->Num?>" data-title="<?=$item->Title;?>" data-parent="" data-type="<?=$item->ItemType;?>" data-reference="<?=$item->Objects_Id;?>" data-referencetitle="<?=$item->getDestination();?>" data-link="<?=$item->Link;?>" data-status="<?=$item->ItemStatus;?>" style="cursor:default;">
					<td class="title"><?=$item->Title;?></td>
					<td><?=$item->ItemType;?></td>
					<td><?=$item->getDestination();?></td>
					<td><?=$item->ItemStatus;?></td>
					<td class="drag" style="cursor:move"><i class="fa-solid fa-ellipsis-vertical"></i></td>
				</tr>
<?php
		if( $item->hasChilds() ) {
			foreach ($item->Items as $subitem) {
				?>
				<tr class="sub-tr item" id="item_<?=$subitem->Num?>" data-num="<?=$subitem->Num?>" data-parent="<?=$item->Num;?>" data-title="<?=$subitem->Title;?>" data-type="<?=$subitem->ItemType;?>" data-reference="<?=$subitem->Objects_Id;?>" data-referencetitle="<?=$subitem->getDestination();?>" data-link="<?=$subitem->Link;?>" data-status="<?=$subitem->ItemStatus;?>" style="cursor:default;">
					<td><i class="fa-solid fa-l fa-2xs ms-1 me-1"></i><?=$subitem->Title;?></td>
					<td><?=$subitem->ItemType;?></td>
					<td><?=$subitem->getDestination();?></td>
					<td><?=$subitem->ItemStatus;?></td>
					<td class="drag" style="cursor:move"><i class="fa-solid fa-ellipsis-vertical"></i></td>
				</tr>
<?php
			}
		}
	}
}
?>
				</tbody>
			</table>
		</div>
	</div>
 
</div>
<!-- New item Modal -->
<div class="modal fade" id="itemModal" tabindex="-1" aria-labelledby="itemModal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="itemModalTitle">Nuevo menú</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form id="itemForm">
					<input type="hidden" name="Menus_Id" value="<?=$menu->Id;?>">
					<input type="hidden" name="Num" id="num" value="">
					<div class="mb-3">
						<label class="form-label">Pertenece a:</label>
						<select class="form-select" id="parent" name="MenusItems_Num" aria-label="item type">
							<option value="">[Principal]</option>
						</select>
					</div>
					<div class="mb-3">
						<label class="form-label">Título</label>
						<input type="text" class="form-control" id="title" name="Title">
					</div>
					<div class="mb-3">
						<label class="form-label">Tipo</label>
						<select class="form-select" id="itemtype" name="ItemType" aria-label="item type">
							<option value="none">Sin enlace</option>
							<option value="reference">Referencia</option>
							<option value="link">Link externo</option>
							<option value="separator">Separador</option>
						</select>
					</div>
					<div class="mb-3" id="item_object" style="display: none;">
						<label class="form-label">Destino referencia</label>
						<input type="text" id="object" class="form-control" data-type="" data-class="" data-title="" placeholder="Buscar ficha contenido..." autocomplete="off" name="Objects_Id">
					</div>
					<div class="mb-3" id="item_link" style="display: none;">
						<label class="form-label">Destino link</label>
						<input type="text" class="form-control" id="link" name="Link">
					</div>
					<div class="mb-3">
						<div class="form-check form-switch">
							<input class="form-check-input" type="checkbox" role="switch" id="itemstatus" name="status">
							<label class="form-check-label" for="itemstatus">Habilitado</label>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-primary" onclick="saveItem()">Guardar</button>
			</div>
		</div>
	</div>
</div>