<script type="text/javascript">

function up(type, group, dt)
{
	url = '<?=$url->get('/ajax/up/');?>' + '?t=' + type + '&g=' + group + '&d=' + dt;
	fetch(url)
	.then(function(response){
		if( response.ok )
		{
			response.json().then(function(data) {
				if(data[0].exito == 1)
				{
					var newNode   = document.getElementById("d-"+group+"-"+dt);
					var parentDiv = document.getElementById("d-"+group+"-"+dt).parentNode;
					var sp2       = document.getElementById("d-"+group+"-"+data[0].aux);
					parentDiv.insertBefore(newNode, sp2);
					return false;
				}
			});
		}
	});

	return false;
}

function down(type, group, dt)
{
	url = '<?=$url->get('/ajax/down/');?>' + '?t=' + type + '&g=' + group + '&d=' + dt;
	fetch(url)
	.then(function(response){
		if( response.ok )
		{
			response.json().then(function(data) {
				if(data[0].exito == 1)
				{
					var newNode   = document.getElementById("d-"+group+"-"+dt);
					var parentDiv = document.getElementById("d-"+group+"-"+dt).parentNode;
					var sp2       = document.getElementById("d-"+group+"-"+data[0].aux);
					parentDiv.insertBefore(newNode, sp2.nextSibling);
					return false;
				}
			});
		}
	});

	return false;
}
</script>

<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/types/typedata/') . $type->Id?>" class="btn btn-sm btn-primary">Nuevo Campo</a>
				<a href="<?=$url->get('/types/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
				<a href="<?=$url->get('/types/edit/') . $type->Id;?>" class="btn btn-sm btn-primary"><i class="far fa-edit"></i> Editar</a>
				<a href="<?=$url->get('/types/delete/') . $type->Id;?>" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/types/')?>">Tipos de contenido</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="float-start">
				<h2 class="mb-0"><?=$type->Name;?></h2>
			</div>
		</div>
	</div>
</div>
<div class="container_fluid">
    <div class="row content p-3">
        <div class="col">
<!--         	<div class="row">
        		<div class="col">
	        		<a href="" class="btn btn-sm btn-primary mb-3">Nuevo campo</a>
	        		<a href="" class="btn btn-sm btn-primary mb-3">Eliminar campo</a>
	        		<a href="" class="btn btn-sm btn-primary mb-3">Nuevo grupo</a>
	        		<a href="" class="btn btn-sm btn-primary mb-3">Eliminar grupo</a>
        		</div>
        	</div>
 -->        

<?php if(count($groups) > 0):?>
	<ul class="nav nav-tabs">
		<li class="d-flex me-3">
			<a href="<?=$url->get('/types/group/') . $type->Id;?>" class="btn btn-sm btn-primary align-self-start"><i class="fas fa-plus"></i></a>
		</li>
		<?php $primero = true;?>
		<?php foreach($groups as $group):?>
			<li class="nav-item">
				<button class="nav-link <?php if($primero):?>active<?php endif;?>" data-bs-toggle="tab" href="#group_<?=$group->Id;?>">
					<?=$group->Title;?>
					<a href="<?=$url->get('/types/group/') . $type->Id.'?g='.$group->Id;?>"><i class="far fa-edit mx-2 pe-2 border-right"></i></a>
				</button>
			</li>
			<?php if($primero):?>
				<?php $primero = false;?>
			<?php endif;?>
		<?php endforeach;?>
	</ul>
	<div class="tab-content" id="dataTabs">
		<?php $primero = true;?>
		<?php foreach($groups as $group):?>
 			<div class="tab-pane bg-white <?php if($primero):?>active<?php endif;?>" id="group_<?=$group->Id;?>">
 				<?php if(count($group->getTypesData()) > 0):?>
 					<table class="table">
						<thead>
							<tr>
								<th width="30%">Tipo</th>
								<th width="35%">Nombre</th>
								<th width="35%">Título</th>
								<th colspan="2"></th>
							</tr>
						</thead>
						<tbody id="g-<?=$group->Id;?>">
							<?php $n = 0;?>
							<?php foreach($group->getTypesData() as $data):?>
								<tr id="d-<?=$group->Id;?>-<?=$data->Id;?>" onclick="window.location.href = '<?=$url->get('/types/typedata/' . $type->Id . '?d=' . $data->Id);?>'">
									<?php $n++;?>
									<td><?=$data->getTypeElement()->Name;?></td>
									<td><?=$data->Name;?></td>
									<td><?=$data->Title;?></td>
									<td>
										<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); up(<?=$type->Id;?>, <?=$group->Id;?>, <?=$data->Id;?>);"><i class="fas fa-angle-up"></i></a>
									</td>
									<td>
										<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); down(<?=$type->Id;?>, <?=$group->Id;?>, <?=$data->Id;?>)"><i class="fas fa-angle-down"></i></a>
									</td>
								</tr>
							<?php endforeach;?>
						</tbody>
					</table> 
 				<?php else:?>
 					<p>Grupo no tiene campos asociados.</p>
 				<?php endif;?>
 			</div>
			<?php if($primero):?>
				<?php $primero = false;?>
			<?php endif;?>
		<?php endforeach;?>
	</div>
<?php else:?>
	<ul class="nav nav-tabs">
		<li class="d-flex me-3">
			<a href="<?=$url->get('/types/group/') . $type->Id;?>" class="btn btn-sm btn-primary align-self-start"><i class="fas fa-plus"></i></a>
		</li>
	</ul>
<?php endif;?>

		</div>
	</div>
</div>