<script type="text/javascript">

function up(type, group, dt)
{
	url = '<?=$url->get('/ajax/up/');?>' + '?t=' + type + '&g=' + group + '&d=' + dt;
	fetch(url)
	.then(function(response){
		if( response.ok )
		{
			response.json().then(function(data) {
				if(data[0].exito == 1)
				{
					var newNode   = document.getElementById("d-"+group+"-"+dt);
					var parentDiv = document.getElementById("d-"+group+"-"+dt).parentNode;
					var sp2       = document.getElementById("d-"+group+"-"+data[0].aux);
					parentDiv.insertBefore(newNode, sp2);
					return false;
				}
			});
		}
	});

	return false;
}

function down(type, group, dt)
{
	url = '<?=$url->get('/ajax/down/');?>' + '?t=' + type + '&g=' + group + '&d=' + dt;
	fetch(url)
	.then(function(response){
		if( response.ok )
		{
			response.json().then(function(data) {
				if(data[0].exito == 1)
				{
					var newNode   = document.getElementById("d-"+group+"-"+dt);
					var parentDiv = document.getElementById("d-"+group+"-"+dt).parentNode;
					var sp2       = document.getElementById("d-"+group+"-"+data[0].aux);
					parentDiv.insertBefore(newNode, sp2.nextSibling);
					return false;
				}
			});
		}
	});

	return false;
}
</script>

<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/types/typedata/') . $type->Id?>" class="btn btn-sm btn-primary">Nuevo Campo</a>
				<a href="<?=$url->get('/types/group/') . $type->Id;?>" class="btn btn-sm btn-primary">Nuevo Grupo</a>
				<a href="<?=$url->get('/types/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
				<a href="<?=$url->get('/types/edit/') . $type->Id;?>" class="btn btn-sm btn-primary"><i class="far fa-edit"></i> Editar</a>
				<a href="<?=$url->get('/types/delete/') . $type->Id;?>" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/types/')?>">Tipos de contenido</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="float-start">
				<h2 class="mb-0"><?=$type->Name;?></h2>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<div class="col">

<?php if( count($groups) ):?>
<ul class="nav nav-tabs">
<?php if( count($typesdata) ):?>
	<li class="nav-item">
		<button class="nav-link active" data-bs-toggle="tab" href="#group_0">
			[Sin grupo]
		</button>
	</li>
<?php endif;?>
<?php
	$num = 0;
	foreach($groups as $group):
		$num++;
?>
	<li class="nav-item">
		<button class="nav-link <?php if($num == 1 && count($typesdata) == 0):?>active<?php endif;?>" data-bs-toggle="tab" href="#group_<?=$group->Id;?>">
			<?=$group->Title;?>
			<a href="<?=$url->get('/types/group/') . $type->Id.'?g='.$group->Id;?>"><i class="far fa-edit mx-2 pe-2 border-right"></i></a>
		</button>
	</li>
<?php endforeach;?>
</ul>
<?php endif;?>
<div class="tab-content" id="dataTabs">
<?php 
if( count($typesdata) ):
?>
	<div class="tab-pane bg-white active" id="group_0">
		<table class="table">
		<thead>
		<tr>
			<th width="35%">Título</th>
			<th width="35%">Nombre</th>
			<th width="30%">Tipo</th>
			<th colspan="2"></th>
			</tr>
		</thead>
		<tbody id="g-0">
<?php
	foreach($typesdata as $typedata):
?>
		<tr id="d-0-<?=$typedata->Id;?>" onclick="window.location.href = '<?=$url->get('/types/typedata/' . $type->Id . '?d=' . $typedata->Id);?>'">
			<td><?=$typedata->Title;?></td>
			<td><?=$typedata->Name;?></td>
			<td><?=$typedata->getTypeElement()->Name;?></td>
			<td>
				<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); up(<?=$type->Id;?>, 0, <?=$typedata->Id;?>);"><i class="fas fa-angle-up"></i></a>
			</td>
			<td>
				<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); down(<?=$type->Id;?>, 0, <?=$typedata->Id;?>)"><i class="fas fa-angle-down"></i></a>
			</td>
		</tr>
<?php
		if( $typedata->TypesElements_Code == 'table'  ) {
			$tableTypesData = $typedata->getTypesDataTable();
			if( count($tableTypesData) ) {
				foreach($tableTypesData as $typedata)
				{
?>
					<tr class="sub-tr" id="d-0-<?=$typedata->Id;?>" onclick="window.location.href = '<?=$url->get('/types/typedata/' . $type->Id . '?d=' . $typedata->Id);?>'">
						<td><i class="fa-solid fa-l fa-2xs ms-1 me-1"></i><?=$typedata->Title;?></td>
						<td><i class="fa-solid fa-l fa-2xs ms-1 me-1"></i><?=substr($typedata->Name, strpos($typedata->Name, '.') + 1);?></td>
						<td><?=$typedata->getTypeElement()->Name;?></td>
						<td></td>
						<td></td>
					</tr>
<?php
				}
			}
		}
	endforeach;
?>
		</tbody>
		</table>
	</div>
<?php
endif;
if( count($groups) ):
	$num = 0;
	foreach($groups as $group):
		$num++;
?>
	<div class="tab-pane bg-white <?php if($num == 1 && count($typesdata) == 0):?>active<?php endif;?>" id="group_<?=$group->Id;?>">
<?php 
		if(count($group->getTypesData()) > 0):
?>
		<table class="table">
		<thead>
		<tr>
			<th width="35%">Título</th>
			<th width="35%">Nombre</th>
			<th width="30%">Tipo</th>
			<th colspan="2"></th>
		</tr>
		</thead>
		<tbody id="g-<?=$group->Id;?>">
<?php
			foreach($group->getTypesData() as $data):
?>
		<tr id="d-<?=$group->Id;?>-<?=$data->Id;?>" onclick="window.location.href = '<?=$url->get('/types/typedata/' . $type->Id . '?d=' . $data->Id);?>'">
			<td><?=$data->Title;?></td>
			<td><?=$data->Name;?></td>
			<td><?=$data->getTypeElement()->Name;?></td>
			<td>
				<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); up(<?=$type->Id;?>, <?=$group->Id;?>, <?=$data->Id;?>);"><i class="fas fa-angle-up"></i></a>
			</td>
			<td>
				<a href="javascript:void(0);" class="btn btn-sm btn-primary" onclick="event.stopPropagation(); down(<?=$type->Id;?>, <?=$group->Id;?>, <?=$data->Id;?>)"><i class="fas fa-angle-down"></i></a>
			</td>
		</tr>
<?php
			endforeach;
?>
			</tbody>
		</table> 
<?php
		else:
?>
		<p>Grupo no tiene campos asociados.</p>
<?php
		endif;
?>
	</div>
<?php
	endforeach;
endif;
?>
</div>

		</div>
	</div>
</div>