<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/types/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/types/')?>">Tipos de contenido</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Tipos de contenido <span class="badge bg-light"><?=$total;?></span></h2>
		</div>
	</div>
</div>
<div class="container_fluid">
	<div class="row content p-3">
		<div class="col">
			<fieldset>
			<a href="<?=$url->get('/types/');?>" class="btn btn-secondary <?=!isset($_REQUEST["class"]) ? " active" : "";?>">Total <span class="badge bg-light text-secondary"><?=$total;?></span></a>
			<?php foreach($classes as $key => $class):?>
				<a href="<?=$url->get('/types/') . '?class=' . $key;?>" class="btn btn-secondary<?php if(count(Types::getTypesClass($key)) == 0):?> disabled<?php endif;?> <?=isset($_REQUEST["class"]) && $_REQUEST["class"] == $key ? " active" : "";?>"><?=$class;?> <span class="badge bg-light text-secondary"><?=count(Types::getTypesClass($key));?></span></a>
			<?php endforeach;?>
			</fieldset>
		</div>
	</div>
	<div class="row content p-3">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th width="1%"></th>
						<th width="30%">Nombre</th>
						<th width="69%">Descripción</th>
					</tr>
				</thead>
				<tbody>
					<?php if( $types ):?>
						<?php foreach($types as $type):?>
							<tr onclick="window.location.href = '<?=$url->get('/types/data/' . $type->Id);?>'">
								<td><i class="fas fa-<?=$type->Class;?>"></i></td>	
								<td><?=$type->Name;?></td>
								<td><?=nl2br($type->Description);?></td>
							</tr>
						<?php endforeach;?>
					<?php endif;?>
				</tbody>
			</thead>
		</div>
	</div>
</div>