<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/types/')?>">Tipos</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Nuevo Tipo de Contenido</h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
<form action="<?=$url->get('/types/create/')?>" role="form" method="post">
	<p><?php $this->flashSession->output();?></p>
	<div class="mb-3">
		<label for="Name" class="form-label">Nombre</label>
		<?php echo $form->render('Name', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="Description" class="form-label">Descripción</label>
		<?php echo $form->render('Description', ['class' => 'form-control', 'rows' => 2]);?>
	</div>
	<div class="mb-3">
		<label for="Class" class="form-label">Clase</label>
		<?php echo $form->render('Class', ['class' => 'form-select']);?>
	</div>
	<div class="mb-3">
		<label for="Template" class="form-label">Plantilla por defecto</label>
		<?php echo $form->render('Template', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="TypeStatus" class="form-label">Estado</label>
		<?php echo $form->render('TypeStatus', ['class' => 'form-select']);?>
	</div>
	<button type="submit" class="btn btn-primary">Crear</button>
</form>
	</div>
</div>