<script>
function confirmDelete()
{
	if( window.confirm("¿Seguro quiere eliminar el usuario <?=$user->getDisplayName();?>?"))
	{
		return true;
	}
	return false;
}
</script>
<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/users/data/') . $user->Id;?>" class="btn btn-sm btn-primary"><i class="far fa-eye"></i> Ver</a>
				<?php if($user->UserStatus == 'active'):?>
				<a href="<?=$url->get('/users/disable/') . $user->Id;?>" class="btn btn-sm btn-primary">Inhabilitar</a>
				<?php elseif($user->UserStatus == 'disabled'):?>
				<a href="<?=$url->get('/users/active/') . $user->Id;?>" class="btn btn-sm btn-primary">Habilitar</a>
				<?php endif;?>
				<a href="<?=$url->get('/users/delete/') . $user->Id;?>" class="btn btn-sm btn-danger" onclick="return confirmDelete();"><i class="fas fa-trash-alt"></i> Eliminar</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/users/')?>">Usuarios</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<img class="profile-image rounded-circle float-start me-2" src="https://i.pinimg.com/originals/64/78/b4/6478b40ee5f7f169b6d25f914ccfcac2.png" alt="...">
			<div class="profile-name float-start">
				<h2 class="mb-0"><?=$user->getDisplayName();?></h2>
				<span><?=$user->getStatusName();?></span>
			</div>
		</div>
	</div>
</div>
<div class="container_fluid">
	<div class="row content p-3">
		<form action="<?=$url->get('/users/save/')?>" role="form" method="post">
			<?php echo $form->render('Id');?>
			<div class="mb-3">
				<label for="name" class="form-label">Nombre Usuario</label>
				<?php echo $form->render('Username', ['id' => 'username', 'class' => 'form-control']);?>
			</div>
			<div class="mb-3">
				<label for="Pass" class="form-label">Contraseña (Ingrese solo si quiere modificar la contraseña actual)</label>
				<?php echo $this->tag->passwordField(
						[
							"Pass",
							'class' => 'form-control'
						]
					);
				?>
			</div>
			<div class="mb-3">
				<label for="name" class="form-label">Nombre</label>
				<?php echo $form->render('FirstName', ['id' => 'name', 'class' => 'form-control']);?>
			</div>
			<div class="mb-3">
				<label for="name" class="form-label">Apellidos</label>
				<?php echo $form->render('LastName', ['id' => 'lastname', 'class' => 'form-control']);?>
			</div>
			<div class="mb-3">
				<label for="name" class="form-label">E-mail</label>
				<?php echo $form->render('Email', ['id' => 'email', 'class' => 'form-control']);?>
			</div>
			<div class="mb-3">
				<?php foreach($roles as $rol):?>
					<?php 
						$checked = null;
						if(isset($_REQUEST["roles"][$rol->Id]))
						{
							$checked = true;
						}
						elseif($user->hasRol($rol->Id))
						{
							$checked = true;
						}
					?>
					<?php echo $this->tag->checkField(
						    [
								'roles['.$rol->Id.']',
								'value'   => $rol->Id,
								'checked' => $checked,
						    ]
						);
					?>
					<?=$rol->Name;?>
					&nbsp;&nbsp;
				<?php endforeach;?>
			</div>
			<button type="submit" class="btn btn-primary">Guardar</button>
		</form>
	</div>
</div>