<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/users/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/users/')?>">Usuarios</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Usuario Nuevo</h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
<form action="<?=$url->get('/users/create/')?>" role="form" method="post">
	<p><?php $this->flashSession->output();?></p>
	<div class="mb-3">
		<label for="Username" class="form-label">Nombre Usuario</label>
		<?php echo $form->render('Username', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="Pass" class="form-label">Contraseña</label>
		<?php echo $form->render('Pass', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="FirstName" class="form-label">Nombre</label>
		<?php echo $form->render('FirstName', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="LastName" class="form-label">Apellidos</label>
		<?php echo $form->render('LastName', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<label for="Email" class="form-label">E-mail</label>
		<?php echo $form->render('Email', ['class' => 'form-control']);?>
	</div>
	<div class="mb-3">
		<?php foreach($roles as $rol):?>
			<?php 
				$checked = null;
				if(isset($_REQUEST["roles"][$rol->Id]))
				{
					$checked = true;
				}
			?>
			<?php echo $this->tag->checkField(
				    [
						'roles['.$rol->Id.']',
						'value'   => $rol->Id,
						'checked' => $checked,
				    ]
				);
			?>
			<?=$rol->Name;?>
			&nbsp;&nbsp;
		<?php endforeach;?>
	</div>
	<button type="submit" class="btn btn-primary">Crear</button>
</form>
	</div>
</div>