<script>
document.addEventListener('DOMContentLoaded', (event) => {
	const references = document.getElementsByClassName('reference');
	for( var i = 0; i < references.length; i++)
	{
		new ReferenceSelect(references[i]);
	}

});
</script>
<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Herramientas</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/import/')?>">Importar</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Importar contenido</h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<form action="<?=$url->get('/import/process')?>" role="form" method="post" enctype='multipart/form-data'>
			<?php $this->flash->output();?>
			<div class="mb-3">
				<label for="folder" class="form-label">Web destino</label>
				<?=$this->tag->select(['web', $webs, 'using' => ['Id', 'Name'], 'class' => 'form-select']);?>
			</div>
			<div class="mb-3">
				<label for="folder" class="form-label">Carpeta destino</label>
				<?=$this->tag->textField(['folder', 'class' => 'form-control reference', 'data-class' => 'folder']);?>
			</div>
			<div class="mb-3">
				<label for="type" class="form-label">Tipo contenido</label>
				<?=$this->tag->select(['type', $types, 'using' => ['Id', 'Name'], 'class' => 'form-select']);?>
			</div>
			<div class="mb-3">
				<label for="type" class="form-label">Formato archivo</label>
				<?=$this->tag->select(['format', $formats, 'class' => 'form-select']);?>
			</div>
			<div class="mb-3">
				<label for="title" class="form-label">Archivo</label>
				<?=$this->tag->fileField(['file[]', 'class' => 'form-control', 'multiple' => 'true']);?>
			</div>
			<button type="submit" name="create" class="btn btn-primary">Importar</button>
		</form>
	</div>
</div>