<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Herramientas</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/import/')?>">Importar</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Importar contenido - Resultado</h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
	<?php $this->flash->output();?>
	</div>
</div>