<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title><?=$this->tag->getTitle();?></title>
		<!-- Behavioral Meta Data -->
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<!-- css -->
		<link rel="stylesheet" type="text/css" href="<?=$url->get("bootstrap5/css/bootstrap.min.css")?>" />
		<link rel="stylesheet/less" type="text/css" href="<?=$url->get("css/screen.less")?>" media="all" />
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		<!-- js -->
		<script type="text/javascript" src="<?=$url->get("bootstrap5/js/bootstrap.bundle.min.js")?>"></script>
		<script src="//cdn.jsdelivr.net/npm/less@3.13" ></script>
	</head>
	<body>
		<section id="login" class="h-100"><!-- recover -->
			<div class="container-fluid h-100">
				<div class="row justify-content-center h-100">
					<div class="col-xs-12 col-md-6 col-lg-4">
					<?php echo $this->tag->form( array("user/codesubmit", 'class' => '')); ?>
						<div class="card card-login">
							<div class="card-header p-4 text-center">
								<img src="/active/images/wa-logo.png" width="160">
							</div>
							<div class="card-body p-4">
								<?php echo $this->flash->output() ?>
								<div class="mb-3">
									<p>Ingrese a continuación su código de recuperación y su nueva clave de acceso.</p>
								</div>
								<div>
									<label for="code" class="form-label">Código</label>
									<?php echo $form->render('code', array('class' => 'form-control', 'placeholder' => 'Código')); ?>
								</div>
								<div>
									<label for="pass" class="form-label">Nueva contraseña</label>
									<?php echo $form->render('pass', array('class' => 'form-control', 'placeholder' => 'Nueva contraseña')); ?>
								</div>
							</div>
							<div class="card-footer p-4 row">
								<div class="col"><?php echo $form->render('submit', array('class' => 'btn btn-primary btn-block	')); ?></div>
							</div>
						</div>
					</div>
					<?= $this->tag->endForm() ?>
				</div>
			</div>
		</section><!-- end recover -->
	</body>
</html>