<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title><?=$this->tag->getTitle();?></title>
		<!-- Behavioral Meta Data -->
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<!-- css -->
		<link rel="stylesheet" type="text/css" href="<?=$url->get("vendor/twbs/bootstrap/dist/css/bootstrap.min.css")?>" />
		<link rel="stylesheet/less" type="text/css" href="<?=$url->get("css/screen.less")?>" media="all" />
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		<!-- js -->
		<script type="text/javascript" src="<?=$url->get("vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js")?>"></script>
		<script src="//cdn.jsdelivr.net/npm/less@3.13" ></script>
	</head>
	<body>
		<section id="login" class="h-100"><!-- recover -->
			<div class="container-fluid h-100">
				<div class="row justify-content-center h-100">
					<div class="col position-relative">
					<?php echo $this->tag->form( array("user/recoversubmit", 'class' => '')); ?>
						<div class="card col-12 col-sm-6 col-lg-4 col-xl-3 card-login position-absolute top-50 start-50 translate-middle">
							<div class="card-header p-4 text-center">
								<img src="/active/images/active-logo.png" width="160">
							</div>
							<div class="card-body p-4">
								<?php echo $this->flash->output() ?>
								<div class="mb-3">
									<p>Para recuperar su acceso ingrese a continuación el correo electrónico asociado a su cuenta de usuario.</p>
								</div>
								<div>
									<label for="email" class="form-label">Correo electrónico</label>
									<?php echo $form->render('email', array('class' => 'form-control', 'placeholder' => 'E-mail')); ?>
								</div>
							</div>
							<div class="card-footer p-4 row">
								<div class="col"><?php echo $form->render('submit', array('class' => 'btn btn-primary btn-block	')); ?>
								<a href="$url->get('')?>" class="btn btn-secondary btn-block">Volver</a></div>
							</div>
						</div>
					</div>
					<?= $this->tag->endForm() ?>
				</div>
			</div>
		</section><!-- end recover -->
	</body>
</html>