<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/roles/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
				<a href="<?=$url->get('/roles/edit/') . $rol->Id;?>" class="btn btn-sm btn-primary"><i class="far fa-edit"></i> Editar</a>
				<a href="<?=$url->get('/roles/delete/') . $rol->Id;?>" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/roles/')?>">Roles</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="float-start">
				<h2 class="mb-0"><?=$rol->Name;?></h2>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<div class="col">
			<div class="card-body">
				<fieldset>
					<dl class="row">
						<dt class="col-sm-3">Descripción:</dt>
						<dd class="col-sm-9"><?=nl2br($rol->Description);?></dd>
					</dl>
					<?php if(count($rol->getPermissions() > 0)):?>
						<dl class="row">
							<dt class="col-sm-3">Permisos</dt>
						</dl>
						<table class="table">
							<?php $categorie = null;?>
							<?php $primero = true;?>
							<?php foreach($rol->getPermissions() as $permission):?>
								<?php if($categorie != $permission->PermissionsCategories_Id):?>
									<?php if($primero):?>
										<?php $primero = false;?>
									<?php else:?>
										</tbody>
									<?php endif;?>
									<?php $categorie = $permission->PermissionsCategories_Id;?>
									<thead>
										<tr>
											<th colspan="2"><?=$permission->getCategorie()->Title;?></th>
										</tr>
									</thead>
									<tbody>
								<?php endif;?>
								<tr>
									<td><?=$permission->Tittle;?></td>
									<td><?=$permission->Description;?></td>
								</tr>
							<?php endforeach;?>
							</tbody>
						</table>
					<?php endif;?>
				</fieldset>
			</div>
		</div>
	</div>
</div>