<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/roles/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/roles/')?>">Roles</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Roles <span class="badge bg-light"><?=count($roles);?></span></h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th>Rol</th>
						<th>Descripción</th>
					</tr>
				</thead>
				<tbody>
					<?php if( $roles ):?>
						<?php foreach($roles as $rol):?>
							<tr onclick="window.location.href = '<?=$url->get('/roles/data/' . $rol->Id);?>'">
								<td><?=$rol->Name;?></td>
								<td><?=$rol->Description;?></td>
							</tr>
						<?php endforeach;?>
					<?php endif;?>
				</tbody>
			</thead>
		</div>
	</div>
</div>