<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a href="<?=$url->get('/roles/new')?>" class="btn btn-sm btn-primary">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Configuración</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/roles/')?>">Roles</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<h2 class="mb-0">Rol Nuevo</h2>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content p-3">
		<form action="<?=$url->get('/roles/create/')?>" role="form" method="post">
			<p><?php $this->flashSession->output(); ?></p>
			<div class="mb-3">
				<label for="name" class="form-label">Nombre</label>
				<?php echo $form->render('Name', ['id' => 'name', 'class' => 'form-control']);?>
			</div>
			<div class="mb-3">
				<label for="description" class="form-label">Descripción</label>
				<?php echo $form->render('Description', ['id' => 'description', 'class' => 'form-control']);?>
			</div>
			<table class="table">
				<?php foreach($categories as $categorie):?>
					<thead>
						<tr>
							<th colspan="3"><?=$categorie->Title;?></th>
						</tr>
					</thead>
					<?php if(count($categorie->getPermissions() > 0)):?>
						<tbody>
							<?php foreach($categorie->getPermissions() as $permission):?>
								<?php 
									$checked = null;
									if(isset($_REQUEST["permissions"][$permission->Id]))
									{
										$checked = true;
									}
								?>
								<tr>
									<td width="5%">
										<?php echo $this->tag->checkField(
											    [
													'permissions['.$permission->Id.']',
													'value'   => $permission->Id,
													'checked' => $checked,
											    ]
											);
										?>
									</td>
									<td><?=$permission->Tittle;?></td>
									<td><?=$permission->Description;?></td>
								</tr>
							<?php endforeach;?>
						</tbody>
					<?php endif;?>
				<?php endforeach;?>
			</table>
			<button type="submit" class="btn btn-primary">Crear</button>
		</form>
	</div>
</div>