<div class="container_fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a class="btn btn-sm btn-primary" href="">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Contenido</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/media/index/')?>">Medios</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="profile-name float-start">
				<h2 class="mb-0">Medios</h2>
			</div>
		</div>
	</div>
</div>
<div class="container_fluid">
	<div class="row m-0 content">
		<div class="col-12 col-md-3 p-0">
			<!-- div class="search">
				<input type="text" placeholder="Buscar...">
			</div -->
			<ul class="folder-list ps-0">
<?php
if( $folders )
{
	foreach($folders as $folder)
	{
		echo '<li class="folder p-3">'; //active
		echo '<a href="', $url->get('/media/index' . $folder->path), '">';
		echo '<div class="profile-image rounded-circle"><i class="fas fa-folder align-middle"></i></div>';
		echo '<h4>', $folder->name, '</h4>';
		echo '<span>', $folder->files, ' elementos</span>';
		echo '</a></li>';
	}
}
?>
			</ul>
		</div>
		<div class="col-12 col-md-9 p-0 bg-white">
			<!-- div class="search">
				<input type="text" placeholder="Buscar...">
			</div -->
			<div class="files-list row px-3 pb-3 pt-3">
<?php
if( $files )
{
	foreach($files as $file)
	{
		echo '<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3"><div class="file-media text-center">';
		echo '<img class="file-thumb mb-1" src="/medios', $file->path, '">';
		echo '<small>', $file->name, '</small>';
		echo '</div></div>';

	}
}
?>
<!--
<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 0</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 1</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 2</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 3</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 4</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 5</small>
					</div>
				</div>
				<div class="col-12 col-md-4 col-lg-3 col-xl-2 mb-3">
					<div class="file-media text-center">
						<img class="file-thumb mb-1" src="https://app.vinglet.com/default-image.png">
						<small>Medio 6</small>
					</div>
				</div>
			</div>
			<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center">
					<li class="page-item disabled">
						<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
					</li>
					<li class="page-item active"><a class="page-link" href="#">1</a></li>
					<li class="page-item"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item">
						<a class="page-link" href="#">Siguiente</a>
					</li>
				</ul>
			</nav>
-->
		</div>
	</div>
</div>