<div class="container-fluid">
	<div class="row p-3 page-header">
		<div class="col-12">
			<div class="actions float-end">
				<a class="btn btn-sm btn-primary" href="">Nuevo</a>
			</div>
			<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
				<ol class="breadcrumb mb-3 py-1">
					<li class="breadcrumb-item"><small><a href="<?=$url->get('/')?>">Inicio</a></small></li>
					<li class="breadcrumb-item active" aria-current="page"><small>Contenido</small></li>
					<li class="breadcrumb-item active" aria-current="page"><small><a href="<?=$url->get('/media/index/')?>">Medios</a></small></li>
				</ol>
			</nav>
		</div>
		<div class="col-12">
			<div class="profile-name float-start">
				<h2 class="mb-0">Medios</h2>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row content">
		<div class="col-12">
		<div class="p-3 media-route">
				<label class="form-label mb-1">Ruta:</label>
				<div class="input-group">
					<input class="form-control" type="text" placeholder="Ruta" value="/active/media/index/">
					<label class="input-group-text" for="inputGroupFile01"><i class="fa-solid fa-arrow-left-to-line"></i></label>
					<label class="input-group-text" for="inputGroupFile01"><i class="fa-solid fa-arrow-up-from-bracket"></i></label>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-6 col-lg-4 p-0">
			
			
			

			<ul class="folder-list ps-0">
				<?php
				if( $folders )
				{
					foreach($folders as $folder)
					{
						echo '<li class="folder p-3">'; //active
						echo '<a class="d-flex align-items-center" href="', $url->get('/media/index' . $folder->path), '">';
						echo '<div class="profile-image"><i class="fas fa-folder align-middle"></i></div>';
						echo '<div><h4>', $folder->name, '</h4>';
						echo '<span>', $folder->files, ' elementos</span></div>';
						echo '</a></li>';
					}
				}
				?>
			</ul>
		</div>
		<div class="col-12 col-md-6 col-lg-8 p-3 bg-white">
			<!-- div class="search">
				<input type="text" placeholder="Buscar...">
			</div -->
			<div class="files-list row p-3'">
				<?php
				if( $files )
				{
					foreach($files as $file)
					{
						echo '<div class="col-6 col-sm-4 col-md-6 col-lg-3 col-xxl-2 mb-3"><div class="file-media text-center">';
						echo '<img class="file-thumb mb-1" src="/medios', $file->path, '">';
						echo '<small>', $file->name, '</small>';
						echo '</div></div>';

					}
				}
				else {
					echo '<p>No hay archivos de medios en este directorio.</p>';
				}
				?>
				

		</div>
	</div>
</div>