<script>
document.addEventListener('DOMContentLoaded', (event) => {
	var referencia = new ReferenceSelect('data_22');
});
</script>
<div class="content p-3">
<form action="<?=$url->get('/prueba')?>" role="form" method="post">
<div class="row">
	<div class="mb-3">
		<label for="data_22" class="form-label">Edición</label>
		<input type="text" class="form-control reference" name="data[22]" id="data_22" placeholder="Buscar ficha contenido..." autocomplete="off" value="12" data-title="Living in the midst of miasmas: The social issue of Chile between 1880 and 1920">
	</div>
</form>
</div>